site_name: Jooby Hut

nav:
  - Home: index.md
  - Projects:
    - LobsterRemake.md
    - ClashSteels.md
    - Salmon.md
    - FruitNinja.md

theme:
  name: 'material'

plugins:
  - mkdocs-video

markdown_extensions:
  - def_list