site_name: Jooby Hut

nav:
  - Home: index.md
  - Projects:
    - LobsterRemake.md
    - ClashOfSteels.md
    - Salmon.md
    - FruitNinja.md

theme:
  palette:
    scheme: slate
  name: 'material'
  features:
    - navigation.sections
    - navigation.indexes
    - toc.follow

plugins:
  - mkdocs-video

markdown_extensions:
  - def_list
  - toc:
      permalink: true
      title: On this page